version: '3.4'

services:
  notebook: 
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
